/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    MovieCard: typeof import('./src/components/MovieCard.vue')['default']
    MovieRank: typeof import('./src/pages/MovieRank.vue')['default']
  }
}
