/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    MediaCard: typeof import('./src/components/media-card.vue')['default']
    MediaResourceFetcher: typeof import('./src/pages/media-resource-fetcher.vue')['default']
    MediaResourceFetcherSetting: typeof import('./src/pages/media-resource-fetcher-setting.vue')['default']
  }
}
